---
- name: Make home directory
  file: path={{ project_home }} state=directory owner=root group=deploy mode=0771
  tags: home

- name: Create log dir
  file:
    path: '{{ project_log_home }}'
    state: directory
    mode: 0700
    owner: 1000
    group: 1000

- name: Setup home for plugins plugin/home.yml
  with_items: '{{ project_plugins }}'
  include: plugins/{{ item }}/home.yml
