---

- debug: var=project_home
- debug: var=project_dns
- debug: var=project_dns_redirect
- debug: var=project_htaccess

- name: Load vars from plugins if any plugin/vars.yml
  with_items: '{{ project_plugins }}'
  include_vars: plugins/{{ item }}/vars.yml

- name: Combine plugins env vars project_plugin_env
  with_items: '{{ project_plugins }}'
  set_fact:
    project_env: '{{ lookup("vars", "project_" + item + "_env")|combine(project_env) }}'

- name: Configure letsencrypt variable if email is provided
  when: letsencrypt_email is defined
  set_fact:
    project_env: '{{ project_env|combine({"LETSENCRYPT_EMAIL": letsencrypt_email, "LETSENCRYPT_HOST": project_dns}) }}'

- name: Configure extra letsencrypt hostnames if project_dns_redirect
  when: project_dns_redirect
  set_fact:
    project_env: '{{ project_env|combine({"LETSENCRYPT_HOST": project_env["LETSENCRYPT_HOST"] + "," + project_dns_redirect|join(",")}) }}'
